AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Learning Yogi - Serverless Timetable Extraction Platform (PoC2)

  Complete serverless architecture with Lambda, API Gateway, Aurora Serverless, and EventBridge

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Tracing: Active
    Environment:
      Variables:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
        LOG_LEVEL: !Ref LogLevel
        POWERTOOLS_SERVICE_NAME: learningyogi
        POWERTOOLS_METRICS_NAMESPACE: LearningYogi
    Tags:
      Project: LearningYogi
      Environment: !Ref Environment

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - production
    Description: Environment name

  LogLevel:
    Type: String
    Default: INFO
    AllowedValues:
      - DEBUG
      - INFO
      - WARNING
      - ERROR
    Description: Logging level

  AllowedOrigins:
    Type: String
    Default: "*"
    Description: CORS allowed origins (comma-separated)

  DatabasePassword:
    Type: String
    NoEcho: true
    Description: Aurora database password (from SSM Parameter Store)

  JWTSecret:
    Type: String
    NoEcho: true
    Description: JWT secret key (from SSM Parameter Store)

  AnthropicAPIKey:
    Type: String
    NoEcho: true
    Description: Anthropic API key for Claude (from SSM Parameter Store)

  ProvisionedConcurrency:
    Type: Number
    Default: 0
    Description: Provisioned concurrency for API functions (0 = disabled)

Resources:
  ##############################################################################
  # API Gateway - REST API
  ##############################################################################

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub learningyogi-api-${Environment}
      StageName: !Ref Environment
      TracingEnabled: true
      Cors:
        AllowOrigin: !Sub "'${AllowedOrigins}'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      Auth:
        DefaultAuthorizer: LambdaTokenAuthorizer
        Authorizers:
          LambdaTokenAuthorizer:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            FunctionPayloadType: TOKEN
            Identity:
              Header: Authorization
              ValidationExpression: "^Bearer [-0-9a-zA-Z\\._]*$"
              ReauthorizeEvery: 300
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseTemplates:
            application/json: '{"error": "Unauthorized"}'

  ##############################################################################
  # Lambda Functions - Node.js (API Layer)
  ##############################################################################

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub learningyogi-authorizer-${Environment}
      CodeUri: ../backend/lambda-nodejs/
      Handler: dist/handlers/authorizer.handler
      Environment:
        Variables:
          JWT_SECRET: !Ref JWTSecret

  DocumentsAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub learningyogi-documents-api-${Environment}
      CodeUri: ../backend/lambda-nodejs/
      Handler: dist/handlers/documents.handler
      Timeout: 30
      MemorySize: 512
      ReservedConcurrentExecutions: 100
      ProvisionedConcurrencyConfig:
        !If
          - HasProvisionedConcurrency
          - ProvisionedConcurrentExecutions: !Ref ProvisionedConcurrency
          - !Ref AWS::NoValue
      Environment:
        Variables:
          DATABASE_URL: !Sub "postgresql://learningyogi:${DatabasePassword}@${AuroraCluster.Endpoint.Address}:5432/learningyogi"
          S3_BUCKET: !Ref DocumentsBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DocumentsBucket
        - Statement:
            - Effect: Allow
              Action:
                - rds-data:ExecuteStatement
                - rds-data:BatchExecuteStatement
              Resource: !GetAtt AuroraCluster.Arn
      Events:
        ListDocuments:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/documents
            Method: GET
        GetDocument:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/documents/{documentId}
            Method: GET
        CreateUpload:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/documents/upload
            Method: POST
        DeleteDocument:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/documents/{documentId}
            Method: DELETE

  TimetablesAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub learningyogi-timetables-api-${Environment}
      CodeUri: ../backend/lambda-nodejs/
      Handler: dist/handlers/timetables.handler
      Environment:
        Variables:
          DATABASE_URL: !Sub "postgresql://learningyogi:${DatabasePassword}@${AuroraCluster.Endpoint.Address}:5432/learningyogi"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - rds-data:ExecuteStatement
              Resource: !GetAtt AuroraCluster.Arn
      Events:
        GetTimetable:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/timetables/{timetableId}
            Method: GET
        UpdateTimetable:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/timetables/{timetableId}
            Method: PUT
        ListTimetables:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/timetables
            Method: GET

  ValidatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub learningyogi-validator-${Environment}
      CodeUri: ../backend/lambda-nodejs/
      Handler: dist/handlers/validator.handler
      Timeout: 30
      Environment:
        Variables:
          DATABASE_URL: !Sub "postgresql://learningyogi:${DatabasePassword}@${AuroraCluster.Endpoint.Address}:5432/learningyogi"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - rds-data:ExecuteStatement
              Resource: !GetAtt AuroraCluster.Arn
        - EventBridgePutEventsPolicy:
            EventBusName: default

  ##############################################################################
  # Lambda Functions - Python (Processing Layer)
  ##############################################################################

  ClassifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub learningyogi-classifier-${Environment}
      CodeUri: ../backend/lambda-python/
      Handler: src.handlers.classifier.handler
      Runtime: python3.11
      Timeout: 60
      MemorySize: 1024
      Environment:
        Variables:
          S3_BUCKET: !Ref DocumentsBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentsBucket
        - EventBridgePutEventsPolicy:
            EventBusName: default

  OCRProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub learningyogi-ocr-processor-${Environment}
      CodeUri: ../backend/lambda-python/
      Handler: src.handlers.ocr_processor.handler
      Runtime: python3.11
      Timeout: 300
      MemorySize: 2048
      EphemeralStorage:
        Size: 1024
      Environment:
        Variables:
          S3_BUCKET: !Ref DocumentsBucket
          USE_CLOUD_VISION: false
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DocumentsBucket
        - EventBridgePutEventsPolicy:
            EventBusName: default

  LLMProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub learningyogi-llm-processor-${Environment}
      CodeUri: ../backend/lambda-python/
      Handler: src.handlers.llm_processor.handler
      Runtime: python3.11
      Timeout: 120
      MemorySize: 512
      Environment:
        Variables:
          S3_BUCKET: !Ref DocumentsBucket
          ANTHROPIC_API_KEY: !Ref AnthropicAPIKey
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentsBucket
        - EventBridgePutEventsPolicy:
            EventBusName: default

  ##############################################################################
  # S3 Bucket for Documents
  ##############################################################################

  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub learningyogi-documents-${Environment}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionOldDocuments
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: GLACIER
          - Id: DeleteProcessedResults
            Status: Enabled
            ExpirationInDays: 30
            Prefix: processed/
      VersioningConfiguration:
        Status: Enabled

  ##############################################################################
  # Aurora Serverless v2 - PostgreSQL
  ##############################################################################

  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Sub learningyogi-${Environment}
      Engine: aurora-postgresql
      EngineVersion: 14.6
      EngineMode: provisioned
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 16
      MasterUsername: learningyogi
      MasterUserPassword: !Ref DatabasePassword
      DatabaseName: learningyogi
      BackupRetentionPeriod: 7
      PreferredBackupWindow: 03:00-04:00
      PreferredMaintenanceWindow: sun:04:00-sun:05:00
      StorageEncrypted: true
      EnableHttpEndpoint: true

  AuroraInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub learningyogi-${Environment}-instance
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: db.serverless
      Engine: aurora-postgresql
      PubliclyAccessible: false

  ##############################################################################
  # EventBridge Rules
  ##############################################################################

  DocumentUploadedRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub learningyogi-document-uploaded-${Environment}
      Description: Trigger processing when document is uploaded
      EventPattern:
        source:
          - custom.learningyogi
        detail-type:
          - Document Uploaded
      State: ENABLED
      Targets:
        - Arn: !GetAtt ClassifierFunction.Arn
          Id: ClassifierTarget

  ##############################################################################
  # Step Functions State Machine
  ##############################################################################

  DocumentProcessingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub learningyogi-processing-${Environment}
      DefinitionUri: ../infrastructure/statemachine.asl.json
      DefinitionSubstitutions:
        ClassifierFunctionArn: !GetAtt ClassifierFunction.Arn
        OCRProcessorFunctionArn: !GetAtt OCRProcessorFunction.Arn
        LLMProcessorFunctionArn: !GetAtt LLMProcessorFunction.Arn
        ValidatorFunctionArn: !GetAtt ValidatorFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ClassifierFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref OCRProcessorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref LLMProcessorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ValidatorFunction

Conditions:
  HasProvisionedConcurrency: !Not [!Equals [!Ref ProvisionedConcurrency, 0]]

Outputs:
  ApiGatewayUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
    Export:
      Name: !Sub ${AWS::StackName}-ApiUrl

  DocumentsBucketName:
    Description: S3 bucket for documents
    Value: !Ref DocumentsBucket
    Export:
      Name: !Sub ${AWS::StackName}-DocumentsBucket

  DatabaseEndpoint:
    Description: Aurora cluster endpoint
    Value: !GetAtt AuroraCluster.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseEndpoint

  StateMachineArn:
    Description: Document processing state machine ARN
    Value: !Ref DocumentProcessingStateMachine
    Export:
      Name: !Sub ${AWS::StackName}-StateMachineArn
